name: Deploy Flow Builder

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Instala deps según lockfile disponible
      - name: Install deps (npm/pnpm/yarn)
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable pnpm
            pnpm install --no-frozen-lockfile
          elif [ -f yarn.lock ]; then
            corepack enable yarn
            yarn install --no-immutable
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Upload dist to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/**"
          target: "/var/www/flow-builder"
          strip_components: 1

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            chown -R www-data:www-data /var/www/flow-builder
            find /var/www/flow-builder -type d -exec chmod 755 {} \;
            find /var/www/flow-builder -type f -exec chmod 644 {} \;
            nginx -t && systemctl reload nginx
